// Signals data - extracted from the prototype SIGNALS array (em-dashes cleaned).
export interface SigAsset { icon: string; label: string; sub: string }
export interface SigTimeline { who: string; platform: string; msg: string; time: string; status: string; statusColor: string }
export interface Signal {
  id: string; title: string; acct: string; desc: string
  risk: 'High Risk' | 'Watch' | 'Positive'; delta: string; deltaColor: string
  time: string; via: string; tags: string[]
  assets: SigAsset[]; timeline: SigTimeline[]
}

export const SIGNALS: Signal[] = [
  { id: 's1', title: 'Silent Stall - Acme Corp', acct: 'acme', desc: 'Buyer dark 8 days. Email opened 3x no reply. Champion may have lost internal backing.', risk: 'High Risk', delta: '-8%', deltaColor: 'var(--danger)', time: '4h ago', via: 'Email', tags: ['Exec Unresponsive', 'Champion at Risk'],
    assets: [{ icon: 'email', label: 'Re-engagement email', sub: 'Personalized to Sarah Chen, CFO' }, { icon: 'doc', label: 'ROI value summary', sub: '3.2x return data for Acme' }, { icon: 'brief', label: 'Executive escalation brief', sub: 'CRO-ready with risk timeline' }],
    timeline: [{ who: 'Sarah Chen (CFO)', platform: 'Gmail', msg: '"We need to discuss pricing before committing to renewal." Sent 8d ago, opened 3x, no reply.', time: '8 days ago', status: 'No response', statusColor: 'var(--danger)' }, { who: 'James Park (VP Eng)', platform: 'Slack', msg: '"Technical integration confirmed. Waiting on legal."', time: '5 days ago', status: 'Positive', statusColor: 'var(--ok)' }, { who: '#account-updates', platform: 'Slack', msg: '"Decision maker unresponsive 6 days. Escalation path unclear."', time: '1 day ago', status: 'Internal flag', statusColor: 'var(--danger)' }] },
  { id: 's2', title: 'Competitor Mention - Meridian Labs', acct: 'meridian', desc: '"Also evaluating Gong and Clari" - confirmed on call.', risk: 'High Risk', delta: '-6%', deltaColor: 'var(--danger)', time: '1d ago', via: 'Call', tags: ['Competitor Eval', 'Multi-Vendor'],
    assets: [{ icon: 'doc', label: 'Competitive battle card', sub: 'Popsicle vs Gong vs Clari comparison' }, { icon: 'email', label: 'Differentiation follow-up', sub: 'Email highlighting unique value' }, { icon: 'brief', label: 'Executive alignment note', sub: 'CRO brief on competitive threat' }],
    timeline: [{ who: 'Alex Park (CEO)', platform: 'Zoom', msg: '"We are looking at alternatives. Gong and Clari both came up."', time: '1 day ago', status: 'Competitor signal', statusColor: 'var(--danger)' }, { who: 'Dana Wu (VP Product)', platform: 'Slack', msg: '"Usage has dropped. Not sure if the team is fully adopting."', time: '3 days ago', status: 'Usage decline', statusColor: 'var(--warn)' }] },
  { id: 's3', title: 'Legal Loop-in - Axion Partners', acct: 'axion', desc: '"Loop in our legal team first" on Slack. Adds 3-5 weeks.', risk: 'High Risk', delta: '-5%', deltaColor: 'var(--danger)', time: '1d ago', via: 'Slack', tags: ['Legal Blocker', '+3-5 Weeks'],
    assets: [{ icon: 'doc', label: 'Pre-approved redline contract', sub: 'Simplified terms for fast legal review' }, { icon: 'email', label: 'Legal fast-track email', sub: 'Direct to Axion legal contact' }, { icon: 'brief', label: 'Timeline impact analysis', sub: 'Close date scenarios with legal delays' }],
    timeline: [{ who: 'Marcus Webb (VP Eng)', platform: 'Slack', msg: '"Need to loop in legal before we can sign anything."', time: '1 day ago', status: 'Legal hold', statusColor: 'var(--warn)' }, { who: 'Legal Team', platform: 'Email', msg: 'Contract redlines sent Nov 14. No response.', time: '3 days ago', status: 'No response', statusColor: 'var(--danger)' }] },
  { id: 's4', title: 'Price Flinch - TechVault Inc', acct: 'techvault', desc: '"Check with finance first" via WhatsApp.', risk: 'Watch', delta: '-4%', deltaColor: 'var(--warn)', time: '7h ago', via: 'WhatsApp', tags: ['Budget Concern', 'Price Sensitivity'],
    assets: [{ icon: 'doc', label: 'Phased pricing proposal', sub: '60% start, expand after ROI proven' }, { icon: 'doc', label: 'ROI calculator for CFO', sub: 'Custom savings projection for TechVault' }, { icon: 'email', label: 'Finance-friendly summary', sub: 'One-pager for budget approval' }],
    timeline: [{ who: 'Jamie Torres (VP Eng)', platform: 'WhatsApp', msg: '"Let me check with finance - the number feels high for this quarter."', time: '7 hours ago', status: 'Price signal', statusColor: 'var(--warn)' }, { who: 'Procurement', platform: 'Gmail', msg: '"Budget review in progress. Vendor shortlist being reassessed."', time: '2 days ago', status: 'Budget flag', statusColor: 'var(--warn)' }] },
  { id: 's5', title: 'Budget Stall - TechFlow Inc', acct: 'techflow', desc: '"Need to check with finance" on Zoom discovery call.', risk: 'Watch', delta: '-3%', deltaColor: 'var(--warn)', time: '3h ago', via: 'Zoom', tags: ['Budget Stall', 'Multi-thread'],
    assets: [{ icon: 'doc', label: 'Phased pricing breakdown', sub: '3-phase implementation plan' }, { icon: 'email', label: 'CFO intro request', sub: 'Direct finance engagement email' }, { icon: 'brief', label: 'Business case one-pager', sub: 'ROI + cost-of-delay analysis' }],
    timeline: [{ who: 'Lena Ford (COO)', platform: 'Zoom', msg: '"CFO mentioned need to check with finance during the call."', time: '3 hours ago', status: 'Budget concern', statusColor: 'var(--warn)' }] },
  { id: 's6', title: 'Renewal Risk - Vertex Systems', acct: 'vertex', desc: 'Procurement flagged timeline question. Proposal under review.', risk: 'Watch', delta: '-2%', deltaColor: 'var(--warn)', time: '1d ago', via: 'Gmail', tags: ['Procurement Review'],
    assets: [{ icon: 'email', label: 'Timeline clarification', sub: 'Detailed implementation roadmap' }, { icon: 'doc', label: 'Proposal FAQ', sub: 'Pre-answers to common procurement questions' }],
    timeline: [{ who: 'Dana Kim (CRO)', platform: 'Gmail', msg: '"Proposal received. Procurement will review this week."', time: '2 days ago', status: 'Under review', statusColor: 'var(--blue)' }] },
  { id: 's7', title: 'Fast-track Signal - Nexus AI', acct: 'nexus', desc: 'CTO forwarded proposal to legal with "let us fast-track this". PO likely this week.', risk: 'Positive', delta: '+3%', deltaColor: 'var(--ok)', time: '34m ago', via: 'Gmail', tags: ['Buyer Active', 'Legal Clear'],
    assets: [{ icon: 'email', label: 'PO follow-up', sub: 'Gentle nudge for PO generation' }, { icon: 'doc', label: 'Onboarding prep', sub: 'Pre-configured environment details' }],
    timeline: [{ who: 'Priya Sharma (CTO)', platform: 'Gmail', msg: '"Sent the proposal to legal. They should turn it around quickly."', time: '34 minutes ago', status: 'Fast-tracking', statusColor: 'var(--ok)' }] },
]

// Asset preview bodies (em-dashes cleaned). Keyed by asset label.
export const ASSET_BODIES: Record<string, string> = {
  'Re-engagement email': 'Subject: Quick check-in - your Q1 pipeline\n\nHi Sarah,\n\nI noticed it has been a few days since we connected. I have prepared a quick ROI summary showing 3.2x return for your team, based on your actual usage data.\n\nWould a brief 10-minute call this week work? I can also send a video walkthrough if that is easier.\n\nBest,\nAndy',
  'ROI value summary': 'EXECUTIVE SUMMARY: ROI Analysis - Acme Corp\n\n- Annual value delivered:       $1.4M\n- Time saved per rep/month:     26 hours\n- Revenue protected this Q:     $560K\n- Churn signals caught:         14 signals\n- Avg intervention time:        3.4 days\n\nRecommendation: 2-year lock-in at 12% discount ($422K vs $480K)\n\nFull breakdown available on request.',
  'Executive escalation brief': 'ESCALATION BRIEF - Acme Corp\nPrepared for: CRO Review\nDate: May 17, 2026\n\nSITUATION\nSarah Chen (CFO) has been unreachable for 8 days. Last positive contact was QBR 3 weeks ago. Pricing objection raised in final call.\n\nRISK\n- ARR at stake: $480K\n- Churn probability: 87% by Day 30 if uncontacted\n- Pattern match: 82% historical churn rate at this stage\n\nACTION REQUIRED\n- CRO-to-CFO call within 48h\n- Frame as strategic partnership review\n- Lead with: ROI data ($1.4M delivered), competitive advantage, timeline\n\nTALKING POINTS\n1. Value delivered this year vs renewal cost\n2. Risk of switching (integration + learning curve)\n3. Exclusive 12% discount for 2-year renewal',
  'Competitive battle card': 'POPSICLE vs GONG vs CLARI\nCompetitive Intelligence - May 2026\n\nReal-time signals:   Popsicle Live  | Gong Batch | Clari No\nMulti-channel:       Popsicle 7 src | Gong Calls | Clari CRM\nAI response kits:    Popsicle Auto  | Gong No    | Clari No\nWhatsApp monitoring: Popsicle Yes   | Gong No    | Clari No\nRevenue Loop:        Popsicle Unique| Gong No    | Clari No\nChurn prediction:    Popsicle 94%   | Gong 72%   | Clari 68%\n\nKEY WIN ARGUMENT:\nPopsicle catches signals 3x faster than Gong and covers channels Clari cannot access.',
  'Differentiation follow-up': 'Subject: One thing we do that Gong cannot\n\nHi Alex,\n\nI know you are evaluating Gong. Fair, they are a solid call recording tool.\n\nHere is what is different: Popsicle monitors Gmail, Slack, AND WhatsApp simultaneously. Gong only sees calls. That means we caught 14 signals in your pipeline this month that Gong would have missed entirely.\n\nWould 15 minutes to show you side-by-side be worth it before your final decision?\n\nAndy',
  'Legal fast-track email': 'Subject: Contract - simplified version attached\n\nHi Marcus,\n\nI understand legal review takes time. I have attached a simplified redline that removes the three clauses most commonly flagged in legal cycles.\n\nMost teams review this version in 3-5 business days vs the standard 14-21 days.\n\nLet me know if your legal team needs a call with ours to accelerate.\n\nBest,\nAndy',
  'Pre-approved redline contract': 'POPSICLE LABS - SIMPLIFIED CONTRACT ADDENDUM\n\nThis fast-track addendum replaces the following standard clauses to accelerate legal review:\n\n1. DATA PROCESSING: Standard DPA applies (GDPR/CCPA compliant)\n2. LIABILITY CAP: 12 months of fees\n3. TERMINATION: 30-day notice, either party\n4. IP OWNERSHIP: Customer retains all data\n\nAll other terms per MSA dated [original date] remain unchanged.\n\nReview time target: 3-5 business days',
  'Phased pricing proposal': 'PRICING PROPOSAL - PHASED ENTRY\n\nOption A - Standard\n$6,000/month - $72K ARR - Full access from Day 1\n\nOption B - Phased (Recommended)\nPhase 1 (Months 1-3): $3,600/month - 60% of full access\nPhase 2 (Months 4+): $6,000/month - Full access\nFirst 90 days to prove ROI before full commitment\n\nOption C - Annual Lock-in\n$5,280/month (12% discount) - $63.4K ARR\nBest value for confirmed long-term use\n\nAll options include: 7 integrations, unlimited signals, dedicated CSM',
  'PO follow-up': 'Subject: PO - ready to support whenever you need\n\nHi Priya,\n\nJust a gentle nudge, I know legal is reviewing. We are fully ready on our end: implementation team is standing by, environment is pre-configured for Nexus AI.\n\nIf it would help to have our legal team hop on a quick call with yours to answer questions, just say the word.\n\nLooking forward to kicking this off!\n\nAndy',
}
